workflow:
  steps:
    custom_step:
      id: 'did-webs'
      type: 'did-webs'
      description: 'Generating DID:Webs'
      domain: 'futureforg.ing/dids'
      aid: 'EGZiuJbg73lpE9WFD7bUBIJviAkdU4pSabMbX8DhlHW2'
