workflow:
  steps:
    custom_step:
      id: 'did-webs'
      type: 'did-webs'
      description: 'Generating DID:Webs'
      host: 'futureforg.ing'
      aid: 'EGZiuJbg73lpE9WFD7bUBIJviAkdU4pSabMbX8DhlHW2'
      path: '/dids'
      port: 8080
